# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d6e6560986cd596c0b67712a21314059b232113ebbb95fb28d37b8eebce688013d026639617aea393f4e7aaf04e53c0a46059742a8ac2b7c9a1393949d2cbb4

test:
  secret_key_base: 2b9c9ac52723d859ad14fc91223ea7f58cf86269ab154571fe39244d85a943b73736556610b6118334d8a0a6ee5c042d309c7b3800f777d5c8ed38df3fa37fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
